version: '2.20.2'
services:
  db: 
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: erasmus_connect
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PORT: 5432
      NODE_ENV: development
    ports: 
      - "4000:4000" # host:container

volumes:
  pgdata: